version: '3.8'

services:
    db:
        image: "postgres:latest"
        container_name: "todo_db"
        environment:
            POSTGRES_DB: todo_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgrespw
        ports:
            - "5432:5432"