spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/todo_db
        username: postgres
        password: postgrespw
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update